version: "2.0"

services:
  webapp:
    #build: .
    image: node:9-alpine
    volumes:
    - .:/frontend
    entrypoint: /bin/sh
    command: -c "cd /frontend && yarn && yarn start"
    ports:
    - "3000:3000"
    working_dir: /frontend
  # runapp:
  #   extends:
  #     service: webapp
  #   ports:
  #   - "3000:3000"
  #   working_dir: /frontend
  #   command:
  #   - yarn start
  production-build:
    #build: .
    image: node:9-alpine
    volumes:
    - .:/frontend
    entrypoint: /bin/sh
    command: -c "yarn && yarn build"
    ports:
    - "3000:3000"
    working_dir: /frontend
  # runapp:
  #   extends:
  #     service: webapp
  #   ports:
  #   - "3000:3000"
  #   working_dir: /frontend
  #   command:
  #   - yarn start

  production-build:
    #build: .
    image: nginx
    volumes:
    - .:/frontend
    - .docker/nginx/conf:/etc/nginx/sites
    entrypoint: /bin/sh
    command: -c "yarn && yarn build"
    ports:
    - "3000:3000"
    working_dir: /frontend
