version: "2.0"

services:
  vulcan-web-dev:
    image: node:9-alpine
    volumes:
    - .:/frontend
    entrypoint: /bin/sh
    command: -c "cd /frontend && yarn && yarn start"
    ports:
    - "3000:3000"
    working_dir: /frontend

  vulcan-prod-build:
    image: node:9-alpine
    volumes:
    - .:/frontend
    entrypoint: /bin/sh
    command: -c "yarn && yarn build"
    working_dir: /frontend

  vulca-web-prod:
    image: nginx:alpine
    volumes:
    - ./build:/usr/share/nginx/html/visa
    - ./nginx.conf:/etc/nginx/conf.d/vulcan.conf
    ports:
    - "80:80"
